### ISSUE TITLE
How to delete duplicates and old devices

### ISSUE THREAD

**Issue by vadimvh** [josh-/CloudyTabs#20]
Hello Josh, is there any way to delete duplicates and old devices?

![shot_2014-10-05_a_11_13_06](https://cloud.githubusercontent.com/assets/8273684/4518060/379f54be-4c70-11e4-8108-267b4611ef29.jpg)

**Comment by josh-** [comment]
CloudyTabs reads iCloud's internal sync data, so iCloud is still trying to sync tabs for these old/duplicate devices for one reason or another. Perhaps try turning off "Safari" in iCloud preferences for these old devices? (If you still have them)

**Comment by josh-** [comment]
However I really like @GaryKing's suggestion about hiding devices that haven't had any activity for a week so I'll implement that and push that in version 1.6. Thanks guys :smile:
