### ISSUE TITLE
Open All Tabs From [device] only opens the first 4 tabs from that device

### ISSUE THREAD

**Issue by bryson** [josh-/CloudyTabs#23]
It does open tabs, but not all tabs. Always the first four tabs in Safari on whichever device I choose. 

iOS 8.1, Yosemite.

**Comment by josh-** [comment]
Thanks guys – I can also reproduce this bug. It appears that it's a regression in the way that Yosemite opens URLs with NSWorkspace's [`openURLs: withAppBundleIdentifier: options: additionalEventParamDescriptor: launchIdentifiers:`](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSWorkspace_Class/index.html#//apple_ref/occ/instm/NSWorkspace/openURLs:withAppBundleIdentifier:options:additionalEventParamDescriptor:launchIdentifiers:) method. I've [filed a bug](http://openradar.appspot.com/19407043) with Apple and have created a hacky workaround that I'll push soon.
