### ISSUE TITLE
CloudyTabs (v1.4) won't "update" the list, nor show the tabs from other devices or the menu 

### ISSUE THREAD

**Issue by jjarava** [josh-/CloudyTabs#24]
Hi!

Been using CloudyTabs for a while, but recently I've noticed that I don't get the "menu" at the bottom, and the tab list doesn't seem to be updated.

This is my current "Cloudy Tabs" menu:
![cloudytabs - tab list shown not complete - 2014-11-13_12-37-33](https://cloud.githubusercontent.com/assets/2682444/5027712/5b2cd61e-6b32-11e4-813a-4638359834e6.jpg)

But as you can see in the "Cloud" tabs in Safari, I have more tabs open on my iPhone, and on my iPad:

![cloudytabs - tab list in safari shows many more tabs - 2014-11-13_12-38-45](https://cloud.githubusercontent.com/assets/2682444/5027727/835f5526-6b32-11e4-97f6-5758636d6115.jpg)

I haven't found any way to "reset" the user preferences; I've tried deleting the CloudyTabs dir within $HOME/Library/Application Support/, the file com.joshparnham.CloudyTabs.plist witihin $HOME/Library/Preferences and the $HOME/Library/Caches/com.joshparnham.CloudyTabs to see if that way I got it to "reset" itself but no luck!

Looking at $HOME, the only references I see to CloudyTabs are some crash reports:

./Downloads/CloudyTabs - Open iCloud Browser Tabs in other browsers - v1.3- CloudyTabs.zip
./Downloads/CloudyTabs - Open iCloud Browser Tabs in other browsers - v1.4- CloudyTabs.zip
./Library/Application Support/CrashReporter/CloudyTabs_B79AF85A-BA3F-5818-B7AF-B94A22A2F469.plist
./Library/Logs/DiagnosticReports/.CloudyTabs_2014-11-02-160712_Mac-JJJ.crash.plist
./Library/Logs/DiagnosticReports/.CloudyTabs_2014-11-05-145621_Mac-JJJ.crash.plist
./Library/Logs/DiagnosticReports/CloudyTabs_2014-11-02-160712_Mac-JJJ.crash
./Library/Logs/DiagnosticReports/CloudyTabs_2014-11-05-145621_Mac-JJJ.crash

But it's quite a pain that CloudyTabs won't work; I'm used to having whatever I've been "reading" in my commute available when I get to my Mac.

OSX 8.1; Mavericks

Regards

**Comment by josh-** [comment]
Thanks for reporting this guys – I've just published [version 1.5](https://github.com/josh-/CloudyTabs/releases/tag/v1.5) which should fix this (I believe it was due to the app's improper handling of multi-byte URLs). Could you please update to that and let me know if the issue persists.

**Comment by sillygwailo** [comment]
I haven't had any problems like this since upgrading to 1.5. Go ahead and close this.

**Comment by jjarava** [comment]
I should've closed this a while ago - it's working for me for quite a hit of time now.

**Comment by jjarava** [comment]
So yes please close the issue (I haven't seen a way to close it myself!)
