### ISSUE TITLE
CloudyTabs loses devices and controls

### ISSUE THREAD

**Issue by dweade** [josh-/CloudyTabs#25]
I've been using CloudyTabs for a bit over a month. On my Macbook Pro, it suddenly stopped showing more than a single device (my iPhone) and lost the controls at the bottom to option such as "open all from X device". I'm also running a different iCloud tab opener on it successfully, so it didn't impede my workflow.

However, the other opener corrupted on my Mac Pro (running Mountain Lion) and I can't even delete and reinstall, so CloudyTabs has been a savior. However, as of today, I"m having the same problem. I can see all of my iPhone tabs, but I cannot open all of them or access any of the additional features. All I see is the name of my iPhone and a list of open tabs and then the window ends.

I deleted everything and reinstalled, but that hasn't changed how it works. There are other tabs open on my MacBook Pro, so there should be at least another device. Thoughts? and thanks.

**Comment by Walfin** [comment]
same problem with my MacBook. I use 2 IOS devices (iPhone, iPAD mini). Both lists are not up to date any more and the controls are lost. Started some onths ago, all of a sudden. I thought upgrade to Yosemite would help- but not change

**Comment by Walfin** [comment]
installed, tested - works fine (as far as i see in the first minutes:-)

Many thinks!!!

**Comment by Walfin** [comment]
issue could be closed from my side, no problems any more! 

Many thinks

**Comment by josh-** [comment]
Awesome to hear! Cheers :smile:
