### ISSUE TITLE
Version number reporting

### ISSUE THREAD

**Issue by crgmrgn** [josh-/CloudyTabs#27]
As you've chosen to not have an About box …

Would be useful if you reported the version number, possibly by augmenting the tooltip text for "CloudyTabs" to "CloudyTabs (v1.5)", for instance. I appreciate the app uses Sparkle to stay up-to-date, but its handy to quickly discover the version in use.

**Comment by ckolderup** [comment]
@crgmrgn for what it's worth, you can see the version of an OS X app you're using in Finder using the Inspector (Cmd-I or "Get Info" from the File or right-click menu).
