### ISSUE TITLE
Remove a device from the list - how ?

### ISSUE THREAD

**Issue by bigmouthmedia** [josh-/CloudyTabs#28]
I have recently replaced my iPhone and while I reset the last one when handing it to Apple, it seems to have retained the list on CloudyTabs - how do I get rid of it ?

Also, how often does it refresh/update ? Is there a way to expedite that ?

**Comment by sillygwailo** [comment]
Eventually, after about a week, the device will drop off the list if it hasn't been sending updates to iCloud. See #20 for more details.

**Comment by bigmouthmedia** [comment]
Ah ok - hopefully 1.6 from Josh will appear soon !

**Comment by josh-** [comment]
Sorry for the delay – 1.6 is now live guys :smile:
