### ISSUE TITLE
com.apple.Safari.plist Values editing?

### ISSUE THREAD

**Issue by RodrigoCard** [josh-/CloudyTabs#29]
Maybe this is not the best place to ask, but lets go....

I am investigating If I can create a new Device in this list, so maybe I can sync my Firefox Tabs (or any list or URLs I want) to icloud.

Before diving into this,
Do you know if someone already made something related? Some article about this to read?

Thanks

**Comment by josh-** [comment]
No worries, happy to help if I can :smile:. [This Python project](https://github.com/smpanaro/icloud-tabs) attempts to do something similar to what you're asking, however I haven't looked into this myself – as per the disclaimer on that project it might cause data loss on your iCloud account but definitely something worth investigating.

**Comment by josh-** [comment]
Now that https://github.com/josh-/CloudyTabs/commit/4b64bd19f9b59730d5956c5661c9e1c377864757 has landed, it could be interesting to look into the possibility of editing the `CloudTabs.db` file for this purpose as well.
