### ISSUE TITLE
No menu in 1.6 under 10.11.5

### ISSUE THREAD

**Issue by raszi** [josh-/CloudyTabs#36]
As it can be seen in the README there is no menu on my machine.

No quit item, no launch at login item just one item from one of my devices (I have two).

<img width="192" alt="screen shot 2016-07-03 at 8 54 30 pm" src="https://cloud.githubusercontent.com/assets/76983/16547069/65b2ed52-4160-11e6-8706-5e33dfe5959f.png">

**Comment by josh-** [comment]
Hopefully will be fixed in v1.7 which will be released today 👍

**Comment by josh-** [comment]
Released! Hope this fixes the issue but let me know if it hasn't 🤞 

You may have to [download it manually](https://github.com/josh-/CloudyTabs/releases/tag/v1.7) since older version of the app check the update log via HTTP which is no longer supported.

**Comment by raszi** [comment]
Yes, the menu items are there. Thank you!

**Comment by raszi** [comment]
I updated the homebrew cask to point to the new version [here](https://github.com/caskroom/homebrew-cask/pull/39770).

**Comment by josh-** [comment]
Super glad to hear! Thanks so much for updating the cask as well ☺️

Let me know if you discover any further issues!
