### ISSUE TITLE
Export to text file instead of just open in browser

### ISSUE THREAD

**Issue by cliffordp** [josh-/CloudyTabs#40]
If I have 2 devices, I want to be able to export `Device A` to `device-a.txt` or `Device B` to `device-b.txt`

**Comment by josh-** [comment]
Hey mate, sorry for the late response! I'm not sure this would be used enough to be added to CloudyTabs, however with the new [CloudyTabs-Server](https://github.com/josh-/cloudytabs-server) project this can be definitely accomplished 😄 

I've put together [this small Ruby script](https://gist.github.com/josh-/cb84879add88a2202418f70194745596) which will do what you ask. So if you install [CloudyTabs-Server](https://github.com/josh-/cloudytabs-server) by following the [Installation instructions](https://github.com/josh-/cloudytabs-server#installation), start running `cloudytabs-server` and then run `ruby export_tabs.rb` you'll have several `txt` files (of the form `DEVICE_NAME.txt`) placed in your current working directory.

I'll close this issue for now, but let me know what you think 🙌

**Comment by cliffordp** [comment]
@josh- 

I'm at 500 tabs again in my iPhone and came back here to check things out... Just found this. Whoops, sorry I didn't see your reply until now, but thanks much for the help!

Unfortunately, I wasn't able to go the way you suggested due to this issue I just filed: https://github.com/josh-/CloudyTabs-Server/issues/1
