### ISSUE TITLE
macOS 10.14 Mojave Compatibility

### ISSUE THREAD

**Issue by josh-** [josh-/CloudyTabs#48]
### Overview

macOS Mojave introduces new privacy controls which limit the access to "Safari data" (from 1:52:05 in [the keynote](https://developer.apple.com/videos/play/wwdc2018/101)). From 12:00 in the ["Your Apps and the Future of macOS Security" session](https://developer.apple.com/videos/play/wwdc2018/702), it is mentioned that Safari Browsing data is now no longer accessible from the file system, unless they are in the new "Application Data" section of the Privacy preference pane.

### Actions

We need to work out any of these changes impact CloudyTabs and if they are able to be overcome.

**Comment by ambroselittle** [comment]
Just upgraded, and it doesn't seem to load. :(

**Comment by timlockridge** [comment]
> Just upgraded, and it doesn't seem to load. :(

This isn't an ideal solution, but I got the app to load by opening the System Preferences Privacy pane and dragging CloudyTabs into the "Full Disk Access" permissions area.

**Comment by ambroselittle** [comment]
Nice workaround. Works for me, too.  We trust you, @josh- ! :D

**Comment by lekudos** [comment]
Hey!  It works!  The disk permissions method works.  awesome app.  Thanks.

**Comment by ksbrar** [comment]
bump.

**Comment by josh-** [comment]
Hey everyone, I've just released [Version 2.0](https://github.com/josh-/CloudyTabs/releases/tag/v2.0) which should hopefully fix this issue – please let me know if you still have any issues after upgrading 👍

**Comment by ambroselittle** [comment]
Many thanks, @josh-. Works well for me.
