### ISSUE TITLE
In MacOS 10.15 CloudyTabs Doesn't Open

### ISSUE THREAD

**Issue by margot-l** [josh-/CloudyTabs#56]
I've been trying to get this to open in 10.15 beta but it doesn't at all. It'll prompt the security check of 'do you want to open this app you downloaded from the internet' but doesn't go any further.

**Comment by dweade** [comment]
Same here. I've tried reinstalling with no luck.

**Comment by ksbrar** [comment]
Bump.

**Comment by loikein** [comment]
Using MacOS 10.14 with iOS 13  and the new iPadOS, does not work either.

**Comment by zrodriguez89** [comment]
Apple updated security settings. Need to give CloudyTabs full disk access in Security & Privacy. After that it should work (it did for me). That way it can retrieve the data.

**Comment by ksbrar** [comment]
Same issue here as @loikein.

**Comment by loikein** [comment]
Update: 
Add CloudyTabs in Accessibility access (Security & Privacy), and it's working again!
Totally no idea why tho.

**Comment by villaineyed** [comment]
Can confirm this works for MacOS 10.15.3.

**Comment by flxs** [comment]
Cannot get it to show a menu bar icon on 10.15.6. It has the "Full Disk Access" permission and I've forcibly re-started the app. I can see a background process hanging around in Task Manager, but no menu bar icon. I did get to the dialog where it asks whether it should check for updates.

**Comment by josh-** [comment]
Hey everyone, I've just released [Version 2.0](https://github.com/josh-/CloudyTabs/releases/tag/v2.0) which should hopefully fix this issue – please let me know if you still have any issues after upgrading 👍
