### ISSUE TITLE
Latest Mojave supplemenetal update (18G95) may have broken CloudyTabs

### ISSUE THREAD

**Issue by dweade** [josh-/CloudyTabs#57]
I've lost the ability to load CloudyTabs 1.9.1 to my Mac Mini and MacBook Pro, both running 10.14.6 with the latest supplemental updates (18G95). I'm fortunate to have a Hackintosh I've recently updated to Mojave where the second of the supplemental updates failed to install so it's stuck on 18G87. I assumed CT was also not working on that system, so was happy to discover it is. This means I continue to move my tabs from my iOS devices using OneTab.

On my newer computers, I've tried cleaning CT files and data then installing an older version, but to no avail. I'm still testing permissions to see if the update caused a simple problem, but the best way to keeping CT working until it's patched may be to avoid the latest updates. Unless you're running a specific Mac notebook or experiencing issues updating the Apple applications, it doesn't appear necessary.

**Comment by ksbrar** [comment]
Bump.

**Comment by perezf** [comment]
Same problem here. I think that this supplemental update somehow brought Catalina's safari to Mojave (it also broke a lot of Safaris's extensions)

**Comment by markaceto** [comment]
macOS 10.14.6
Safari 13.0.3

I have 2 "Mark's iPhone" lists in Cloudy Tabs (54 each). They were appearing on multiple iOS and macOS devices, where I was able to "delete" them, so they no longer appear in iCloud tabs on those respective devices. However, I can't remove them from Cloudy Tabs.

Where is the log file that Cloudy Tabs is pulling this info?

**Comment by patrickwelker** [comment]
Same problem like in the first three comments. Hoping for a fix.

_macOS 10.13.6, Mac mini Server (Late 2012)_

**Comment by tloredo** [comment]
Same problem for me: MacMini8,1, macOS 10.14.6.

**Comment by wagninger** [comment]
yup, same problem here - I think Apple moved the plist file for the Safari preferences around; This is the output in Terminal:
2020-03-08 07:54:13.604 CloudyTabs[1236:24661] /Users/USER/Library/SyncedPreferences/com.apple.Safari.plist exists? 0 (0)

**Comment by motoservo** [comment]
Sorry, I see the issue was already a ticket. I tried to delete it but don't seem to have that ability.

Here's my notes but added onto this thread instead.

Can't get cloudytabs to launch, seeing some stuff in Console about it being denied by Sandbox. There are other items in the list but I'm guessing that's the one that means the most. Let me know if I should paste the rest of the errors as well. One of them lists a plist file that's missing, which I think is described in an earlier comment here.

Sandbox: CloudyTabs(1245) System Policy: deny(1) file-read-data /Users/Moto/Library/Safari/CloudTabs.db

**Comment by motoservo** [comment]
To anybody who hasn't found the Pull Request that's got the solution detailed in the updated "Read Me". Here's the info what will solve this.

-=-=-
If you find that CloudyTabs fails to start on macOS 10.14 Mojave, try adding CloudyTabs to "Full Disk Access" under `Security & Privacy > Privacy` in your System Preferences (see [Issue #48](https://github.com/josh-/CloudyTabs/issues/48)).

**Comment by josh-** [comment]
Hey everyone, I've just released [Version 2.0](https://github.com/josh-/CloudyTabs/releases/tag/v2.0) which detects when Full Disk Access is required and prompts users to enable it inside the app.

Please let me know if you still have any issues with CloudyTabs 👍
