### ISSUE TITLE
10.13.2 nothing is showing up in 'Open All Tabs From'

### ISSUE THREAD

**Issue by kello45** [josh-/CloudyTabs#59]
I am signed in to iCloud and have opened Chrome and Safari on Macbook Pro...
I have about 30 open tabs on Safari in iOS I'd like to bring over to Chrome on Macbook.

**Comment by ChiliApple** [comment]
same on 10.13.6

**Comment by josh-** [comment]
Hey everyone, I've just released [Version 2.0](https://github.com/josh-/CloudyTabs/releases/tag/v2.0) which should hopefully fix this issue – please let me know if you still have any issues after upgrading 👍

**Comment by ChiliApple** [comment]
Hy, sorry same issue 

Best
